server:
  port: 9093

spring:
  application:
    name: business-service
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  driver-class-name: com.mysql.dbc.Driver
  generate-ddl: true
  profiles:
    active: local
