server:
  port: 9093
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ondemand?allowPublicKeyRetrieval=true&useSSL=false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka



#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://localhost:8081/eureka